### ISSUE TITLE
The NetLogo View's "font size" attribute should be respected

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#180]
Here is "Info Tab Example" in JVM NetLogo:

![jvminfotab](https://cloud.githubusercontent.com/assets/912890/5251178/f103ac6a-7958-11e4-8d59-efa92525365d.png)

Here it is in Tortoise:

![tortoiseinfotab](https://cloud.githubusercontent.com/assets/912890/5251179/f2aa44fc-7958-11e4-8d39-f7522bf92f6c.png)

The text is tiny in the Tortoise version.  The font size for labels and Note widgets should be taking on the value specified in the View's properties.

**Comment by qiemem** [comment]
Note that font size information is contained in the view widget itself, which `/local` doesn't actually get. Since I'm working on the command center for `/tortoise` anyway, I didn't think it would be worth it to make the architectural changes required to get the widget info to `/tortoise`. You can test the fix by opening "Info Tab Example" in `/tortoise` and running `startup()` in the javascript console.

**Comment by TheBizzle** [comment]
* An architectural change (**C**) would need to be made in order to get View information to the page
  * Work is already in progress on a Command Center for that page
  * Therefore, it would not be worthwhile to make change **C** at this time

I'm not following the logic.  Doesn't **C** need to happen no matter what?  How does the WIP on the Command Center affect whether or not **C** should happen right now?

**Comment by qiemem** [comment]
Woops, keep switching `/local` and `/tortoise`. Should've read:

> Note that font size information is contained in the view widget itself, which `/local` doesn't actually get. Since I'm working on the command center for `/tortoise` anyway, I didn't think it would be worth it to make the architectural changes required to get the widget info to `/local`.

The problem is fully fixed for `/tortoise` and for standalone pages.

**Comment by TheBizzle** [comment]
Oh, okay, that makes sense.
