### ISSUE TITLE
Slider number inputs can get pushed off to the side if labels are too big

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Galapagos#198]
For example:

![image](https://cloud.githubusercontent.com/assets/28215/6320802/ddeff53e-baad-11e4-9d3e-e2eb0e210b77.png)

There's got to be a way to make them shrink to fit instead. First thing I'll try will be using flex instead of text-align.

**Comment by psndcsrv** [comment]
I've been encountering this with some models I've been converting -- the sizing in NetLogo is fine, but the sizing in the converted model ends up pushing the value out of view. It's bad enough on most of the models to make them unusable since you can't see what value you're setting. Any word on plans to fix this?

**Comment by TheBizzle** [comment]
I would like to see this fixed very soon.

@qiemem, the JVM NetLogo behavior for this seems like what we should be emulating: always show the value, and truncate the variable name if it doesn't fit.  ([Relevant StackOverflow](http://stackoverflow.com/questions/12649904/css-text-ellipsis-when-using-variable-width-divs))

**Comment by TheBizzle** [comment]
@psndcsrv, this is now fixed on the main server.

**Comment by psndcsrv** [comment]
Great! Much appreciated.
