### ISSUE TITLE
IE: Patches are really blurry

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Galapagos#212]
Demonstration:

![badwsp](https://cloud.githubusercontent.com/assets/912890/6660533/be7c15f8-cb69-11e4-9aab-8065a07edc02.png)

This occurs in both IE10 and IE11.

**Comment by qiemem** [comment]
Patches were originally done by using `drawImage` to scale the pixel data onto a canvas of the correct size. Due to [this bug](https://code.google.com/p/chromium/issues/detail?can=2&q=134040&colspec=ID%20Pri%20M%20Week%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&id=134040), this technique resulted in images strikingly similar to the one here. So I switched to stretching out the pixel canvas itself.

For #154, I'm switching back to scaling with `drawImage` (made possible by that bug being fixed). Hopefully, IE let's you modify the interpolation algorithm used by canvases. [Can I use](http://caniuse.com/#search=pixelated) says they have their own prefixed css attribute to accomplish this (though it's not clear to me if this refers just to `img` elements or to canvases as well).

**Comment by qiemem** [comment]
Ah woops, looks like I switched the scaling techniques. [See this comment.](https://github.com/NetLogo/Galapagos/blob/a48724cc01f44e66a2fffdda411db580960e1c85/app/assets/javascripts/TortoiseJS/agent/view.coffee#L345)

So, I wanted to just scale with CSS, but that bug prevented me. So we're scaling with `drawImage` instead. [Looks like we just need to add an `ms` prefix to the `imageSmoothingEnabled` context property](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled#Browser_compatibility), like we do with [all the other browsers](https://github.com/NetLogo/Galapagos/blob/a48724cc01f44e66a2fffdda411db580960e1c85/app/assets/javascripts/TortoiseJS/agent/view.coffee#L375).

Again, I'll try to fix this with #154.

**Comment by qiemem** [comment]
I've confirmed that

    @ctx.msImageSmoothingEnabled = false;

fixes the problem. I'll fix it with #154, since that's changing all the rendering code anyway.

**Comment by qiemem** [comment]
Uh oh, [disabling image smoothing was added to IE in 11](https://msdn.microsoft.com/en-us/library/ie/dn265062(v=vs.85).aspx). It's pretty fundamental to making patch rendering not horrifically slow... so not really sure what to do about that.

**Comment by TheBizzle** [comment]
Still an issue with IE10 and Chrome 20, but I'm not quite convinced that those can/should be fixed.  It's trickier in these old browsers.
