### ISSUE TITLE
`resize-world` and `set-patch-size` don't change view widget size

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Galapagos#227]
In NetLogo, they actually change the view widget itself, but in Tortoise, we only change the aspect ratio of the canvas.

**Comment by TheBizzle** [comment]
This is more relevant, now that the `set-patch-size` primitive is implemented over in Tortoise.

**Comment by TheBizzle** [comment]
There are a couple of related problems here.

First, `.netlogo-view-container` is statically sized.  `.netlogo-canvas` sizes itself to fit into the `.netlogo-view-container`.  So, while the patch size gets updated correctly and the element is told the new dimensions that it needs to fit, it doesn't actually resize, since it insists on taking up all of the space in its parent, no matter what, and its parent (`.netlogo-view-container`) didn't get resized.  This can be mitigated by making `.netlogo-view-container`'s dimensions to be `auto`.  This allows resizes of the View to work, except for when the View attempts to become bigger than its original size.

The fact that the View cannot grow from its original size is caused by the bigger, harder-hitting problem here, which is that `.netlogo-widget-container` is statically sized.  Because of this, the widget area does not change with the size/positions of its content.  Its size is determined once (when the model is loaded) and then never reassessed.  Obviously, this isn't a strategy that's going to work going forward, once we have widget authoring, and, honestly, it doesn't even really work right now, since `resize-world` and `patch-size` are broken by this approach.

Addressing this issue will involve something along the lines of dynamically resizing `.netlogo-widget-container`.

**Comment by qiemem** [comment]
`.netlogo-widget-container` is already set to have width equal to the right most coordinate of the widgets:

https://github.com/NetLogo/Galapagos/blob/3c903a1793110e4f8281a56b56f243be0aa0c5e6/app/assets/javascripts/TortoiseJS/agent/widgets.coffee#L34

https://github.com/NetLogo/Galapagos/blob/3c903a1793110e4f8281a56b56f243be0aa0c5e6/app/assets/javascripts/TortoiseJS/agent/widgets.coffee#L310

We may be able to just tweak this so that it's being set off a function (of the same expression) and then tell ractive that it should be recalculated when widget dimensions change using ractives dependency declaration thing. Alternatively, we could set out a change listener on the appropriate dimensions and manually re-set the property.

**Comment by qiemem** [comment]
Note that `.netlogo-model` will also have to be similarly resized.

Also, I'm pretty sure I set up the iframe in `/launch` to resize automatically (when the child passes a message up), so that part, at least, should be easy.

**Comment by TheBizzle** [comment]
> `.netlogo-widget-container` is already set to have width equal to the right most coordinate of the widgets

Yes, but that is only being done once, and I'm not sure it's very wise of us to size that container by looking only at the sizes of the widget objects.  I would think it should be sized be off of the sizes of the DOM elements inside of it.

**Comment by qiemem** [comment]
> I would think it should be sized be off of the sizes of the DOM elements inside of it.

All the elements are relatively positioned now (and I imagine they will continue to be), so we can't get the browser to automatically resize based on contents. That leaves manually resizing, which, I believe, amounts to pretty much the same thing as manually resizing off the dimensions of the widgets, except for a few key differences:

- The widget dimensions are in the ractive model, and thus changes changes in them can easily be reacted to. That said, what we react to doesn't have to be the same thing we resize off of, so I suppose we could react to netlogo dimension changes, but calculate size off DOM.
- The widget dimensions do *not* take into account DOM margins and such. I think that's okay though; we shouldn't have any widgets exceeding their netlogo dimensions since that would lead to somewhat bad differences between NetLogo and NLW: tightly packed widgets in NetLogo could obscure each other in NLW. Thus, margins should always be 0 anyway. Thus, I think we can ignore this point.

My current plan of attack is to stick in ractive observers on NetLogo dimensions and to recalculate size off of NetLogo dimension as well. I think this is the most straightforward approach as we don't have to get into icky DOM size/position calculation stuff. That stuff always sucks and leads to browser compatibility problems and such. However, should we want to do that later, the change should be relatively easy (outside of DOM ickiness).

I haven't been in this code in a while though, so this plan could change quickly.
