### ISSUE TITLE
Widget differences between JVM NetLogo, NLW

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/Galapagos#269]
Per https://github.com/NetLogo/Galapagos/pull/211. 
Most widgets look just about exactly like their NetLogo counterpart, but there are a few differences:
* note widgets with opaque backgrounds / different font colors
* vertical sliders
* Buttons with shortcut keys
* Buttons with agent types
![screen shot 2015-07-21 at 1 22 58 pm](https://cloud.githubusercontent.com/assets/143198/8809054/c4a7b7e2-2fab-11e5-9f6d-3d5b2fa7c7a9.png)
I'm not sure how many of these ommissions are intentional ("we're not putting this in NetLogo Web") vs unimplemented ("we haven't gotten around to it yet"). @qiemem , perhaps you could provide a bit more detail.

**Comment by TheBizzle** [comment]
> * note widgets with opaque backgrounds / different font colors
* vertical sliders
* Buttons with shortcut keys
* Buttons with agent types

All of these ought to be supported at some point.

**Comment by qiemem** [comment]
> note widgets with opaque backgrounds / different font colors

I had no idea. Not intentional. That said... I think I prefer the transparent backgrounds. Font colors should definitely be supported.

> vertical sliders

Intentionally de-prioritized. #171 

> Buttons with shortcut keys

Targeting 1.1. #262 

> Buttons with agent types

I think this works... We just don't show visually indicate. Maybe we should. And do a forever button icon while we're at it.

The other big differences I see:

- Multi-line widget names

Should be fixed. They should use ellipses like buttons do now.

- The "change" button on multi-line input boxes

I *really* want input boxes to remain editable without hitting change. That said, also having "change" to open up a larger editor for easier editing seems like a good idea to me.

- Hiding widget names for monitor

I didn't know this was possible. This should be supported.

Are there any others I'm not seeing?

**Comment by TheBizzle** [comment]
> * Hiding widget names for monitor
>
> I didn't know this was possible. This should be supported.

I don't think that's intentional behavior.  Looks to me like it's just an artifact of abusing font size in JVM NetLogo.

**Comment by mrerrormessage** [comment]
That's correct, JVM NetLogo isn't great about small font sizes. You can't actually shrink/grow the height of monitor widgets, except by changing the font size.

**Comment by SethTisue** [comment]
> I think I prefer the transparent backgrounds

Every note has a checkbox specifying whether it is to be transparent or opaque, so NetLogo Web should (eventually) support both.

**Comment by TheBizzle** [comment]
Also note that there should be syntax highlighting in Inputs that aren't basic string Inputs.

**Comment by TheBizzle** [comment]
Stuff that remains here:

  * Agent buttons should have icons that show them as such
  * "Forever" buttons should have icons that show them as such
  * Command/reporter string Inputs should be syntax highlighted
  * Multiline Inputs should support editing the text in a larger editor

None of these remaining problems seems very critical to me.  Moving to 1.1 milestone.

**Comment by TheBizzle** [comment]
I recently addressed some more of this.  Here's what remains:

  * Command/reporter string Inputs should be syntax highlighted
  * Multiline Inputs should support editing the text in a larger editor

**Comment by TheBizzle** [comment]
With the completion of #313, the only problem that remains here is

> Command/reporter string Inputs should be syntax highlighted

I'm going to close this issue and open a separate one just for that.
