### ISSUE TITLE
in the “select a model…” menu everything has an extra “modelslib/“ in front of it

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/Galapagos#273]
Robert says it is "superfluous, but it is intentional", but regardless, for 1.0, it's pretty weird, and it's very prominent

**Comment by TheBizzle** [comment]
It's not clear to me that/why it is intentional.  @mrerrormessage, could you clarify?

**Comment by mrerrormessage** [comment]
When I added in the "demomodels" folder for testing different features, I differentiated between modelslib and demomodels. We can change it (for instance, doing a fallback on lookup), but it was done intentionally. Whoever removes "modelslib" should also ensure that the demo models still work after the fix is made.

**Comment by TheBizzle** [comment]
I assume that, with Chosen, you can set a display value for showing in the dropdown menu and a hidden "true" value for the item.  If that's the case, you can just make the hidden value the true URL.

**Comment by mrerrormessage** [comment]
Yes, that's correct, I should have just trimmed out "modelslib" [when adding text to the constructed options](https://github.com/NetLogo/Galapagos/blob/master/app/assets/javascripts/models.coffee#L14-L15). I'll fix this and filter out models that don't compile.

**Comment by mrerrormessage** [comment]
This is addressed in #275

**Comment by TheBizzle** [comment]
Fixed by c9629480eeb6f6055535e840ce59ca1b0e916824
