### ISSUE TITLE
plotxy issue

### ISSUE THREAD

**Issue by JusteRaimbault** [NetLogo/Galapagos#346]
The primitive plotxy has some issue when used in web plots : if two points not drawn at the same time happen to have the same x coordinates, the plot connects them when it shouldn't.

The basic following model produces this issue, when trying to draw a circle :

```
globals [
 xx
 yy
]

to setup
  ca
  crt 1 [setxy -10 0 set heading 90]
  reset-ticks
end

to go
  ask one-of turtles [
    fd 10 * pi / 360 rt 0.5 
  ]
  tick
end

to-report x
  report [xcor] of one-of turtles
end

to-report y
  report [ycor] of one-of turtles
end
```

with plot having pen update code `plotxy x y`

**Comment by TheBizzle** [comment]
Thanks for reporting this.  You're right that there's a discrepancy.  That said, I don't agree that NetLogo Web should be expected to do the same thing in this case as desktop NetLogo does.  Desktop NetLogo allows you to draw arbitrary lines in the plotting area.  However, I don't know of any JS "plotting library" that allows the drawing of arbitrary lines in the plotting space, and I think that doing so would simply subvert the meaning of the term "line plot" to do so.  Plot widgets aren't really meant to be arbitrary drawing canvases; they're for showing specific kinds of relations between data.

In terms of finding a workaround for the problem presented here, if you want to draw arbitrary points on a plot, scatter plots would get the job done, and I think they make a lot more sense for this use case, anyway.  Better yet, turtle pens could be used to draw the turtle's path directly within the View widget, rather than putting it in a plot.  That said, I suspect that the model given here is a toy model, so maybe these suggestions aren't very useful.  If I saw the real model that prompted this, though, I could probably provide better suggestions or maybe even become convinced that something needs to change.

As it stands, though, I don't think it's important for us to support this exact scenario, so I'm closing this as "won't fix".

Related: #235
