### ISSUE TITLE
"Nothing named ? has been defined." only in NetLogo Web

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#355]
https://www.netlogoweb.org/web?https://800-dot-m4a-gae-hrd.appspot.com/p/aMmsj0pEjbOf9OObqNrC46.nlogo

runs fine with the NetLogo 6.0 executable (no conversion offered or needed). And yet the web version complains that there a something named ?. I searched for ? and all the ones I saw were part of a name.

**Comment by TheBizzle** [comment]
I definitely agree that better error messages would be nice.

The `?` in question is on the line `[ ask ? [setxy 0 0`, in `layout-circle-replacement`, at the bottom of your code (line 1349).  Note that this procedure might not even be necessary for you anymore, since NetLogo Web now implements `layout-circle`.

Worthy of note is that I actually *do* get this same error in NetLogo 6, and that's what I expected to happen, since NetLogo 6 removed `?` as a special variable as a part of the anonymous procedure syntax overhaul.

**Comment by ToonTalk** [comment]
Thanks. Sorry about that. I accidentally tested a slightly different version in the executable version.
