### ISSUE TITLE
Graph not drawn but is drawn fine by NetLogo executable

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Galapagos#356]
https://www.netlogoweb.org/web?https://800-dot-m4a-gae-hrd.appspot.com/p/cscISeXH4oJLCMbLm9Go55.nlogo

The Wealth Distribution graph is either empty or looks like this:

![image](https://cloud.githubusercontent.com/assets/2138696/22818426/2447ed62-efa8-11e6-8473-1d174bcdbb1a.png)

While the executable shows

![image](https://cloud.githubusercontent.com/assets/2138696/22818471/51e660aa-efa8-11e6-89f0-e8973b2474ad.png)

**Comment by ToonTalk** [comment]
By NetLogo executable I meant NetLogo 6.0 Windows 7 64-bit

**Comment by TheBizzle** [comment]
Yeah, so the problem here is one of those "it would be maddening to try and support NetLogo's exact (and sometimes unusual) plotting behavior in every single case" sort of things.  I'll explain the issue in a bit more detail.

Every time there's an iteration through your plotting code, you're starting back at `0, 0` and essentially drawing a new curve/line up to `100, 100` with a new color.  Using the same pen to draw multiple lines is a no-go in NLW, and not something that I want to go through the trouble of allowing.  It makes for code that isn't very semantic about what plot is actually doing, and it's pretty easy to work around in a way that *is* semantic.

That is to say that, in order to get your code doing the same thing in both environments, all you have to do is drop `create-temporary-plot-pen (word "" (round ticks mod 145))` right before the line `set-plot-pen-color round time mod 145`.  If you do that, each line will end up with its own pen, and NetLogo Web will know what to do with it.

**Comment by ToonTalk** [comment]
Thanks. That fixed the problem. By the way create-temporary-plot-pen (word (round ticks mod 145)) works just as well.
