### ISSUE TITLE
Sliders don't always initialize properly

### ISSUE THREAD

**Issue by philipwoods** [NetLogo/Galapagos#376]
NetLogo Web sliders initialize differently depending on whether you open a Web HTML file directly or upload a model to the netlogoweb.org website.  When you build a model in desktop NetLogo and save it as a NetLogo Web file, the Web sliders behave like they're supposed to.  When you go to netlogoweb.org and upload the original NetLogo model, the sliders don't always start out properly.  This is also true when you load a library model from the drop down menu on netlogoweb.org.

This seems to only occur with sliders that have an increment less than 1.  On netlogoweb.org, sliders that should start at non-integer values have their global variable initialized at the correct value, but the position of the slider is rounded to the nearest integer.  I first noticed this in the Daisyworld and Membrane Formation library models, but verified it separately later, shown below.

![opened html](https://user-images.githubusercontent.com/1878604/35700432-9523dbfe-0758-11e8-8bfe-970b22f4f0f2.png)
![uploaded](https://user-images.githubusercontent.com/1878604/35700433-95351a0e-0758-11e8-8674-821b5c7eb280.png)

**Comment by LaCuneta** [comment]
Philip, thanks for all the great details (as usual).  As you discovered, it does have to do with step sizes between 0 and 1.  The easy fix has to do with making sure default step sizes are small enough to allow default values to be set.  The fix is now live in [staging](https://staging.netlogoweb.org) if you want to check it out.  

**Warning: excruciating details below**

The reason it worked in the exported NetLogo desktop version was desktop is using an older version of the Ractive library.  That made it seem like a Ractive bug, but as far as I can tell, this issue isn't caused by Ractive at all.  My best guess then is a fix in Ractive actually allowed the negative result to come through when it wasn't before.

Either way, the core issue is that `input` elements with `type="range"` will round their values when the `step` size wouldn't evenly land on the `value` as so: `<input type="range" min="0" max="1" step="1.0" value="0.8" />`.  This appears to be the behavior in Chrome and Firefox, at least.  That causes the issue seen here, as we were pre-initializing the default value of the step size to `1`, which is bigger than a lot of default values.  The quick fix is to use a much smaller initial step size.  A better fix might to be to make sure we initialize the step size to the correct value right away instead of any default, but that'd be a bigger and more complicated change.
