### ISSUE TITLE
Improve in UI

### ISSUE THREAD

**Issue by sarthak-g** [NetLogo/Galapagos#388]
As NetLogo is quite big organisation so it is important that it's UI must be of standards of modern web and be user friendly

**Comment by sarthak-g** [comment]
So i want to give it's UI a whole new look with respect to modern standard web frontend.Can i contribute towards it?

**Comment by LaCuneta** [comment]
Sarthak,

Thanks for your interest in NetLogo Web!  We do accept outside contributions, if you want to get started you can walk through the [technical details](url
https://github.com/NetLogo/Galapagos/wiki/Technical-Details) and then see our [building and running](url
https://github.com/NetLogo/Galapagos/wiki/Building-and-running) wiki pages.  Then you can check out the issues list if you want to do some work with the code and try to commit a fix.  We are unlikely to accept large changes from an unknown (to us) first-time contributor.

This issue is too general for me to understand the kinds of changes you are proposing.  What specific user interface changes do you think NetLogo Web would benefit from?  Cosmetic changes are not a big priority for us at the moment, improving functionality is a bigger goal.

**Comment by LaCuneta** [comment]
Do you have examples where the alignment and font size of the text are not proper?

**Comment by sarthak-g** [comment]
Like in the left side navigation bar headings like "user models" and  "manuals" should have larger font text as compared to links and a little bit Bold.
And the button label as "Donate" should either have center alignment with respect to navigation bar or starting of button should have same space from left side as that of above texts.
Also navigation links should have "text decoration" as "None"

**Comment by TheBizzle** [comment]
Oh.  You're referring to https://ccl.northwestern.edu/netlogo/ (which has no public repository).  This repository is for https://netlogoweb.org/ .

**Comment by LaCuneta** [comment]
@sarthak-g As TheBizzle said, that's an internal CCL site, so we do not accept contributions for it.  I do appreciate your interest, and we'll make sure to note your suggestions for future updates to it.
