### ISSUE TITLE
Use a proper module system and produce bundled files

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Galapagos#77]
There are a few related tasks here:

1. Add a proper module system for [the Beak front-end view for the NetLogo Web engine](https://github.com/NetLogo/Galapagos/tree/master/app/assets/javascripts/beak).  Right now most things are just [attaching themselves to the global namespace](https://github.com/NetLogo/Galapagos/blob/master/app/assets/javascripts/beak/tortoise.coffee#L207-L208).   
2. Do proper bundling so that there is a single `beak.js` artifact to load instead of [loading each Beak file separately](https://github.com/NetLogo/Galapagos/blob/master/app/views/simulation.scala.html#L57-L101).
3. Produce a dependency bundle as well so we can host/link that instead of each individual dependency script.

We're relatively agnostic on what tech/library/tool to use to accomplish these tasks, as long as it's minimally disruptive to the project and easy to maintain.  

- No RequireJS, please.
- Handling item #1 using [ES6 modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) to avoid introducing any new dependencies would be an attractive solution.

## Original Issue Text Below

I have been converted.

Also, we may want to start using [bower](http://bower.io/) to manage client-side dependencies. Probably better than our current solution of rehosting dependencies on the netlogo server and then maintaining our custom thing for asset management.

**Comment by daviddostal** [comment]
Do you guys mind if I take a stab at this?

I would like to make some improvements to the UI of NLW and this would be a great issue to get familiar with the codebase.

**Comment by LaCuneta** [comment]
Hi @daviddostal !

Thanks for your interest in NetLogo Web.  This issue was a little out of date and I've tweaked the info in it and tried to elaborate a bit.  There are a few pieces here you could work on I listed there.

We actually dropped the RequireJS project in favor of Browserify for [Tortoise](https://github.com/NetLogo/Tortoise), so we'd want to avoid RequireJS again.  Browserify works fine for handling these tasks for us there, but we'd be okay trying a different approach here.

If you want to give a go at any of these tasks, feel free.  If you have questions you can use our [NetLogo Gitter channel](https://gitter.im/NetLogo/NetLogo) or [the NetLogo devel Google Group](https://groups.google.com/g/netlogo-devel) to reach out.

**Comment by daviddostal** [comment]
Hi @LaCuneta, thanks for welcoming me and elaborating on the issue.

I think using ES6 modules is the simplest approach here (and in my opinion preferred over requirejs anyway).

Using ES6 modules would allow doing task 1. and 2. separately without the need to refactor a substantial part of the codebase and introduce a bundler at the same time. And NetLogo Web works only in modern browsers anyway, so browser support [should not be an issue](https://caniuse.com/es6-module).

 I'll start working on task 1. and report back when I've made some progress.

**Comment by LaCuneta** [comment]
Item number 1 (the big one) is complete, thank you @daviddostal !  I'll open new issues for items 2 and 3.
